In [1]:
#Dictionary= Value in terms of a key and pair

In [2]:
d1= {'key1':[1,2,3,4,5,"kirti"],
     'key2' :[7,8,9,10,11,12],
     'key3' :[13,14,15,16,17,18],
     'key4' :[19,20,21,22,23,24]
}

In [3]:
import pandas as pd

In [4]:
df1=pd.DataFrame(d1)

In [5]:
d2= {'key1':[1,2,3,4,5,"kirti"],
     'key2' :[7,8,"Wagh",10,11,12],
     'key3' :[13,14,15,16,17,18],
     'key4' :[19,20,21,"ineuron","pwskills",24]
}

In [6]:
df2=pd.DataFrame(d2)

In [7]:
df1

key1  key2  key3  key4
0      1     7    13    19
1      2     8    14    20
2      3     9    15    21
3      4    10    16    22
4      5    11    17    23
5  kirti    12    18    24

In [8]:
df2

key1  key2  key3      key4
0      1     7    13        19
1      2     8    14        20
2      3  Wagh    15        21
3      4    10    16   ineuron
4      5    11    17  pwskills
5  kirti    12    18        24

In [9]:
#Merge operations with dataframes
pd.merge(df1,df2)

key1 key2  key3 key4
0      1    7    13   19
1      2    8    14   20
2  kirti   12    18   24

In [10]:
pd.merge(df1,df2,how= 'inner', on= 'key1')

key1  key2_x  key3_x  key4_x key2_y  key3_y    key4_y
0      1       7      13      19      7      13        19
1      2       8      14      20      8      14        20
2      3       9      15      21   Wagh      15        21
3      4      10      16      22     10      16   ineuron
4      5      11      17      23     11      17  pwskills
5  kirti      12      18      24     12      18        24

In [11]:
pd.merge(df1,df2,how= 'inner', on= 'key4')

key1_x  key2_x  key3_x key4 key1_y key2_y  key3_y
0      1       7      13   19      1      7      13
1      2       8      14   20      2      8      14
2      3       9      15   21      3   Wagh      15
3  kirti      12      18   24  kirti     12      18

In [12]:
pd.merge(df1,df2,how= 'left', on= 'key4')

key1_x  key2_x  key3_x key4 key1_y key2_y  key3_y
0      1       7      13   19      1      7    13.0
1      2       8      14   20      2      8    14.0
2      3       9      15   21      3   Wagh    15.0
3      4      10      16   22    NaN    NaN     NaN
4      5      11      17   23    NaN    NaN     NaN
5  kirti      12      18   24  kirti     12    18.0

In [13]:
pd.merge(df1,df2,how= 'right', on= 'key4')

/tmp/ipykernel_91/2686434494.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2,how= 'right', on= 'key4')


key1_x  key2_x  key3_x      key4 key1_y key2_y  key3_y
0      1     7.0    13.0      19.0      1      7      13
1      2     8.0    14.0      20.0      2      8      14
2      3     9.0    15.0      21.0      3   Wagh      15
3    NaN     NaN     NaN   ineuron      4     10      16
4    NaN     NaN     NaN  pwskills      5     11      17
5  kirti    12.0    18.0      24.0  kirti     12      18

In [14]:
pd.merge(df1,df2,how= 'outer', on= 'key4')

/tmp/ipykernel_91/2946980083.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2,how= 'outer', on= 'key4')


key1_x  key2_x  key3_x      key4 key1_y key2_y  key3_y
0      1     7.0    13.0      19.0      1      7    13.0
1      2     8.0    14.0      20.0      2      8    14.0
2      3     9.0    15.0      21.0      3   Wagh    15.0
3      4    10.0    16.0      22.0    NaN    NaN     NaN
4      5    11.0    17.0      23.0    NaN    NaN     NaN
5  kirti    12.0    18.0      24.0  kirti     12    18.0
6    NaN     NaN     NaN   ineuron      4     10    16.0
7    NaN     NaN     NaN  pwskills      5     11    17.0

In [15]:
pd.merge(df1,df2,how= 'outer',on= ['key4','key1'])

/tmp/ipykernel_91/1864705398.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2,how= 'outer',on= ['key4','key1'])


key1  key2_x  key3_x      key4 key2_y  key3_y
0      1     7.0    13.0      19.0      7    13.0
1      2     8.0    14.0      20.0      8    14.0
2      3     9.0    15.0      21.0   Wagh    15.0
3      4    10.0    16.0      22.0    NaN     NaN
4      5    11.0    17.0      23.0    NaN     NaN
5  kirti    12.0    18.0      24.0     12    18.0
6      4     NaN     NaN   ineuron     10    16.0
7      5     NaN     NaN  pwskills     11    17.0

In [16]:
d11= {'a':[1,2,3,4,5,"kirti"],
     'b' :[7,8,9,10,11,12],
     'c' :[13,14,15,16,17,18],
     'd' :[19,20,21,22,23,24]
}

In [17]:
d12= {'key1':[1,2,3,4,5,"kirti"],
     'key2' :[7,8,"Wagh",10,11,12],
     'key3' :[13,14,15,16,17,18],
     'key4' :[19,20,21,"ineuron","pwskills",24]
}

In [18]:
df11 = pd.DataFrame(d11)

In [19]:
df12 = pd.DataFrame(d12)

In [20]:
df11

a   b   c   d
0      1   7  13  19
1      2   8  14  20
2      3   9  15  21
3      4  10  16  22
4      5  11  17  23
5  kirti  12  18  24

In [21]:
df12

key1  key2  key3      key4
0      1     7    13        19
1      2     8    14        20
2      3  Wagh    15        21
3      4    10    16   ineuron
4      5    11    17  pwskills
5  kirti    12    18        24

In [22]:
pd.merge(df11,df12, how= 'left', left_on= 'a',right_on='key1')

a   b   c   d   key1  key2  key3      key4
0      1   7  13  19      1     7    13        19
1      2   8  14  20      2     8    14        20
2      3   9  15  21      3  Wagh    15        21
3      4  10  16  22      4    10    16   ineuron
4      5  11  17  23      5    11    17  pwskills
5  kirti  12  18  24  kirti    12    18        24

In [23]:
#join operation 

In [24]:
d10= {'key11':[1,2,3,4,5,"kirti"],
     'key21' :[7,8,9,10,11,12],
     'key31' :[13,14,15,16,17,18],
     'key41' :[19,20,21,22,23,24]
}

In [25]:
d20= {'key1':[1,2,3,4,5,"kirti"],
     'key2' :[7,8,"Wagh",10,11,12],
     'key3' :[13,14,15,16,17,18],
     'key4' :[19,20,21,"ineuron","pwskills",24]
}

In [26]:
df10= pd.DataFrame(d10, index = [1,2,3,4,5,6])

In [27]:
df20 = pd.DataFrame(d20, index = [1,2,3,4,5,'kirti'])

In [28]:
df10

key11  key21  key31  key41
1      1      7     13     19
2      2      8     14     20
3      3      9     15     21
4      4     10     16     22
5      5     11     17     23
6  kirti     12     18     24

In [29]:
df20

key1  key2  key3      key4
1          1     7    13        19
2          2     8    14        20
3          3  Wagh    15        21
4          4    10    16   ineuron
5          5    11    17  pwskills
kirti  kirti    12    18        24

In [30]:
df10.join(df20,how='right')

key11  key21  key31  key41   key1  key2  key3      key4
1         1    7.0   13.0   19.0      1     7    13        19
2         2    8.0   14.0   20.0      2     8    14        20
3         3    9.0   15.0   21.0      3  Wagh    15        21
4         4   10.0   16.0   22.0      4    10    16   ineuron
5         5   11.0   17.0   23.0      5    11    17  pwskills
kirti   NaN    NaN    NaN    NaN  kirti    12    18        24

In [31]:
df10.join(df20)
#left if not taking how any

key11  key21  key31  key41 key1  key2  key3      key4
1      1      7     13     19    1     7  13.0        19
2      2      8     14     20    2     8  14.0        20
3      3      9     15     21    3  Wagh  15.0        21
4      4     10     16     22    4    10  16.0   ineuron
5      5     11     17     23    5    11  17.0  pwskills
6  kirti     12     18     24  NaN   NaN   NaN       NaN

In [32]:
df10.join(df20, how='outer')

key11  key21  key31  key41   key1  key2  key3      key4
1          1    7.0   13.0   19.0      1     7  13.0        19
2          2    8.0   14.0   20.0      2     8  14.0        20
3          3    9.0   15.0   21.0      3  Wagh  15.0        21
4          4   10.0   16.0   22.0      4    10  16.0   ineuron
5          5   11.0   17.0   23.0      5    11  17.0  pwskills
6      kirti   12.0   18.0   24.0    NaN   NaN   NaN       NaN
kirti    NaN    NaN    NaN    NaN  kirti    12  18.0        24

In [33]:
df10.join(df20, how = 'inner')

key11  key21  key31  key41 key1  key2  key3      key4
1     1      7     13     19    1     7    13        19
2     2      8     14     20    2     8    14        20
3     3      9     15     21    3  Wagh    15        21
4     4     10     16     22    4    10    16   ineuron
5     5     11     17     23    5    11    17  pwskills

In [34]:
#difference in merge and join
#join matches the indexes and merge operation based on values.
#Even column name is same we can do merge operation.

In [35]:
pd.concat([df1,df2], axis=0)
#horizontal concatation.

key1  key2  key3      key4
0      1     7    13        19
1      2     8    14        20
2      3     9    15        21
3      4    10    16        22
4      5    11    17        23
5  kirti    12    18        24
0      1     7    13        19
1      2     8    14        20
2      3  Wagh    15        21
3      4    10    16   ineuron
4      5    11    17  pwskills
5  kirti    12    18        24

In [36]:
pd.concat([df1,df2], axis=1)
#if axis =1 then it is column wise.

key1 key2  key3 key4   key1  key2  key3      key4
0      1    7    13   19      1     7    13        19
1      2    8    14   20      2     8    14        20
2      3    9    15   21      3  Wagh    15        21
3      4   10    16   22      4    10    16   ineuron
4      5   11    17   23      5    11    17  pwskills
5  kirti   12    18   24  kirti    12    18        24

# Numpy 

In [37]:
# Numerical Python
# matlab-simulation Purpose

In [38]:
import numpy as np

In [39]:
# In machine learning while building a model Numpy is used
# Random number generation
# for building matrices


In [40]:
l= [1,2,3,4,4]

In [41]:
type(l)

list

In [42]:
# List convert into array 
a=np.array(l)

In [43]:
type(a)

numpy.ndarray

In [44]:
a

array([1, 2, 3, 4, 4])

In [45]:
a1 = np.array([[1,2,3],[3,4,5]])

In [46]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [47]:
a2 = np.array([[[1,2,3],[4,5,6]]])

In [48]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [49]:
a

array([1, 2, 3, 4, 4])

In [50]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [51]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [52]:
a.ndim

1

In [53]:
a1.ndim

2

In [54]:
a2.ndim

3

In [55]:
#Machine Learning only understands array and matrices even not dataframe

In [56]:
a3 = np.array([[[1,2,3], [4,.5,6]],[[1,2,3],[4,.5,6]],[[1,2,3],[4,.5,6]]])

In [57]:
a3

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [58]:
a3.ndim

3

In [59]:
l=[1,2,3,4]

In [60]:
a= np.asarray(l)

In [61]:
m=np.matrix(l)

In [62]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [63]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [64]:
#array is superclass inside numpy, matrix is already a type of array 

In [65]:
#Shallow copy

In [66]:
a

array([1, 2, 3, 4])

In [67]:
a1=a

In [68]:
a1

array([1, 2, 3, 4])

In [69]:
a

array([1, 2, 3, 4])

In [70]:
a[0] = 10

In [71]:
a

array([10,  2,  3,  4])

In [72]:
a1

array([10,  2,  3,  4])

In [73]:
a1[3]= 50

In [74]:
a1

array([10,  2,  3, 50])

In [75]:
a

array([10,  2,  3, 50])

In [76]:
a2=np.copy(a)

In [77]:
a2

array([10,  2,  3, 50])

In [78]:
a2[2] = 30

In [79]:
a2

array([10,  2, 30, 50])

In [80]:
a

array([10,  2,  3, 50])

In [81]:
np.fromfunction(lambda i,j : i==j, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [82]:
np.random.rand(2,3)

array([[0.36835856, 0.35665804, 0.03297264],
       [0.32631521, 0.88034719, 0.95120784]])

In [83]:
np.random.rand(2,3,2)

array([[[0.06955467, 0.64613215],
        [0.34275247, 0.72565086],
        [0.9238181 , 0.58884276]],

       [[0.74021942, 0.42462285],
        [0.85734288, 0.80412666],
        [0.01977769, 0.06234976]]])

In [84]:
np.random.rand(2,3,2,2)

array([[[[0.51869197, 0.51832397],
         [0.61476596, 0.43912298]],

        [[0.78863443, 0.42557168],
         [0.61263937, 0.46159299]],

        [[0.00196916, 0.57964619],
         [0.59553381, 0.66852697]]],


       [[[0.86930528, 0.92927305],
         [0.53820255, 0.95751425]],

        [[0.84582617, 0.24804216],
         [0.42310102, 0.61450635]],

        [[0.92346497, 0.71870161],
         [0.75476586, 0.61978309]]]])

In [85]:
np.random.rand(1,4,4)

array([[[0.47070773, 0.11800706, 0.99334268, 0.12961678],
        [0.46894627, 0.37583669, 0.45633557, 0.30482002],
        [0.03029083, 0.13817802, 0.14826132, 0.9312988 ],
        [0.72817647, 0.51690368, 0.14522995, 0.26860267]]])

In [86]:
np.random.rand(3,4,4)

array([[[0.00190936, 0.64716789, 0.53653814, 0.77698775],
        [0.93935004, 0.90016273, 0.81679892, 0.65643612],
        [0.3029953 , 0.19476441, 0.34814098, 0.22497215],
        [0.95769646, 0.77092033, 0.04267725, 0.72437827]],

       [[0.41516281, 0.80704444, 0.07913891, 0.6984392 ],
        [0.90188603, 0.17755163, 0.45172117, 0.98558628],
        [0.37919477, 0.63878213, 0.34410155, 0.51680719],
        [0.75088741, 0.59979993, 0.04389078, 0.467367  ]],

       [[0.25034421, 0.9205785 , 0.03683756, 0.41095099],
        [0.04461462, 0.22761903, 0.62093352, 0.27698363],
        [0.2587202 , 0.30870286, 0.99975614, 0.33502004],
        [0.1083361 , 0.7177105 , 0.9401404 , 0.89624311]]])

In [87]:
np.random.rand(1,2,4)

array([[[0.96537746, 0.83937131, 0.08281187, 0.09266641],
        [0.42090444, 0.57083514, 0.70817474, 0.42812546]]])

In [88]:
d=np.random.randn(3,4)

In [89]:
d1=np.random.randint(0,10,(4,4,2))

In [90]:
pd.DataFrame(d)

0         1         2         3
0  0.213391  0.778472  2.436616 -1.184238
1  1.424463 -0.254341  0.732474  1.397096
2  0.186629  1.456463 -2.081452  0.401481

In [91]:
d1.reshape(8,4)

array([[0, 8, 1, 0],
       [8, 9, 0, 3],
       [8, 6, 4, 8],
       [9, 2, 1, 9],
       [0, 6, 7, 1],
       [3, 2, 3, 6],
       [5, 0, 4, 0],
       [9, 9, 6, 8]])

In [92]:
d1.reshape(16,2)
#No is multiple of total no in arrays

array([[0, 8],
       [1, 0],
       [8, 9],
       [0, 3],
       [8, 6],
       [4, 8],
       [9, 2],
       [1, 9],
       [0, 6],
       [7, 1],
       [3, 2],
       [3, 6],
       [5, 0],
       [4, 0],
       [9, 9],
       [6, 8]])

In [93]:
d1.reshape(8,-198345)
# 8 is multiple of 32

array([[0, 8, 1, 0],
       [8, 9, 0, 3],
       [8, 6, 4, 8],
       [9, 2, 1, 9],
       [0, 6, 7, 1],
       [3, 2, 3, 6],
       [5, 0, 4, 0],
       [9, 9, 6, 8]])

In [94]:
pd.DataFrame(d1.reshape(32,-19876))

0
0   0
1   8
2   1
3   0
4   8
5   9
6   0
7   3
8   8
9   6
10  4
11  8
12  9
13  2
14  1
15  9
16  0
17  6
18  7
19  1
20  3
21  2
22  3
23  6
24  5
25  0
26  4
27  0
28  9
29  9
30  6
31  8