In [1]:
#1. How to check the normality of the data
#2. Z-test
#3. t-test
#4. Anova test
#5. chi square test

In [2]:
import pandas as pd

In [3]:
#importing the dataset
data=pd.read_csv("https://raw.githubusercontent.com/shrikant-temburwar/Wine-Quality-Dataset/master/winequality-red.csv",sep=';')

In [4]:
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [5]:
data["volatile acidity"]

0       0.700
1       0.880
2       0.760
3       0.280
4       0.700
        ...  
1594    0.600
1595    0.550
1596    0.510
1597    0.645
1598    0.310
Name: volatile acidity, Length: 1599, dtype: float64

In [6]:
import seaborn as sns
sns.distplot(data["volatile acidity"])

C:\Users\DELL\anaconda3\lib\site-packages\seaborn\distributions.py:2619: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)


<AxesSubplot:xlabel='volatile acidity', ylabel='Density'>

In [7]:
#Its a non normal data

In [8]:
sns.distplot(data["citric acid"],kde=True, color="Red")

C:\Users\DELL\anaconda3\lib\site-packages\seaborn\distributions.py:2619: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)


<AxesSubplot:xlabel='citric acid', ylabel='Density'>

#To test normality we have Shapiro Wilk test with respect to p-value i.e if p-value <= 0.05 then we can reject the null hypothesis i.e our data is not nonnormal data distributed.

In [9]:
from scipy import stats
stats.shapiro(data["volatile acidity"])

ShapiroResult(statistic=0.9743340611457825, pvalue=2.686806772838566e-16)

In [10]:
stats.shapiro(data["citric acid"])

ShapiroResult(statistic=0.9552900195121765, pvalue=1.0208196357632134e-21)

#statistic value is nothing put z-value from above values data is nonnormally distributed

In [11]:
from numpy.random import randn
mydata=randn(150)

In [12]:
sns.distplot(mydata)

C:\Users\DELL\anaconda3\lib\site-packages\seaborn\distributions.py:2619: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)


<AxesSubplot:ylabel='Density'>

In [13]:
result = stats.shapiro(mydata)

In [14]:
result

ShapiroResult(statistic=0.9936842322349548, pvalue=0.7575294375419617)

what is my null hypothesis
null hypothesis that the data was drawn from a normal distribution.

In [15]:
if p<=result[1]:
    print("reject the null hypothesis")
else:
    print("accept the null hypothesis")

NameError: name 'p' is not defined

In [16]:
from scipy import stats
stats.normaltest(data["citric acid"])

NormaltestResult(statistic=152.039214793795, pvalue=9.662822259281018e-34)

In [17]:
stats.normaltest(mydata)

NormaltestResult(statistic=1.2258517368237931, pvalue=0.5417634193970056)

#Eg- In a college there is different students.50 student from my colege.their avearge IQ is 110. mean population IQ is 100
standard deviation is 15 
mean population IQ is null hypothesis 
5% significance level i.e 95% Confidence interval.

=> Null hypothesis H0:mu=100

   Alternative hypothesis H1:mu > 100
   
   One tail test or right tail test
   
   Z-score = (110-100)/15 = (xbar-mean)/standard devia 0.66
   
   We have to find critical value from z-table at 0.05 significant level which is 1.65
   
   0.66 > 1.65 i.e z-score(actual vaue) > critical value(table)
   
   we accept the null hypothesis.
   

In [19]:
#Python implementation
from statsmodels.stats.weightstats import ztest

In [ ]:
sample_mean_iq = 110
alpha = 0.05
ci = 95%

In [22]:
mean_std_dev = 15
mean_population = 100

In [24]:
data = mean_std_dev*randn(50)+mean_population

In [27]:
import numpy as np

In [28]:
np.mean(data)

99.16952874138404

In [29]:
np.std(data)

14.47245023754589

In [35]:
null_value = 100

In [36]:
from statsmodels.stats.weightstats import ztest
ztest(data,value = null_value,alternative='larger')

(-0.401680345407598, 0.6560403544382402)

### t-test 
#### one_sample_t_test (with respect to one independent sample)
#### two sample t test (with respect to two independent sample)
#### paired t test (two sample from the sample population on different time interval)

In [ ]:
#ztest vs ttest
#sample size less than 30
# pop var/pop std won't be there

In [24]:
import random
import numpy as np
population = np.random.randint(10,50,50)

In [26]:
sample1 = np.random.choice(population,20)

In [27]:
sample2 = np.random.choice(population,20)

In [28]:
sample1.mean()

32.95

In [30]:
sample2.mean()

30.65

In [ ]:
null_hypothesis = sample mean should be 27.35

In [31]:
my_cricket_score = [22,38,19,15,48,11,10,49,47,38,10,255,46,10,21,24,29,36,25,24]

In [45]:
np.mean(my_cricket_score)

38.85

In [32]:
virat_cricket_score = [33,45,23,25,46,46,49,49,14,14,44,25,31,25,40,30,20,42,37]

In [33]:
(sum(virat_cricket_score))/len(virat_cricket_score)

33.578947368421055

In [34]:
np.mean(virat_cricket_score)

33.578947368421055

In [41]:
import scipy
result = scipy.stats.ttest_1samp(my_cricket_score,25)

In [42]:
result[1]

0.25366531968809647

In [44]:
#p_value<=0.05
#we are going to reject the null hypothesis

In [ ]:
#if p_value we are going to accept the null hypothesis
p_value>0.05

In [ ]:
scipy.stats.ttest_1samp(my_cricket_score,25)

In [46]:
#paired t test (two sample from the sample population on different time interval)
my_cricket_score = [22,38,19,15,48,11,10,49,47,38,10,255,46,10,21,24,29,36,25,24]
virat_cricket_score = [33,45,23,25,46,46,49,49,14,14,44,25,31,25,40,30,20,42,37]

In [48]:
first_sample_mean = np.mean(my_cricket_score)
second_sample_mean = np.mean(virat_cricket_score)

In [49]:
print(first_sample_mean)
print(second_sample_mean)

38.85
33.578947368421055


In [ ]:
my_null_hypothesis = both sample mean will be same

In [50]:
scipy.stats.ttest_ind(my_cricket_score,virat_cricket_score)

Ttest_indResult(statistic=0.4265466135370657, pvalue=0.6721812042455579)

In [51]:
#paired t test- different time interval
my_cricket_score_from_first_inning = [22,38,19,15,48,11,10,49,47,38,10,45,46,10,21,24,29,36,25,24]
my_cricket_score_from_second_inning = [22,38,29,15,18,11,10,49,47,38,50,45,46,40,21,24,29,16,25,24]

In [54]:
print(np.mean(my_cricket_score_from_first_inning))
print(np.mean(my_cricket_score_from_second_inning))

28.35
29.85


In [52]:
scipy.stats.ttest_rel(my_cricket_score_from_first_inning,my_cricket_score_from_second_inning)

Ttest_relResult(statistic=-0.47094573282755464, pvalue=0.6430413877149443)

#chi-square test - For categorigal data
#For numerical dta - ztest,ttest and Anova
#Correlation between numeric feature can be calculated as Pearson correllation and spearman correllation
#if we have x1 and x2 is categorical feature how we check relation between them or dependency -
#So we have to check goodness of fit or implementing a chisquare test .chisquare test is very important for feature selectiondata

In [55]:
import seaborn as sns

In [57]:
dataset=sns.load_dataset('tips')

In [58]:
dataset

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [59]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [60]:
dataset.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [61]:
dataset[['sex','smoker']]

sex smoker
0    Female     No
1      Male     No
2      Male     No
3      Male     No
4    Female     No
..      ...    ...
239    Male     No
240  Female    Yes
241    Male    Yes
242    Male     No
243  Female     No

[244 rows x 2 columns]

In [63]:
dataset_tabole = pd.crosstab(dataset['sex'],dataset['smoker'])

In [95]:
observed_Values=dataset_tabole.values

In [96]:
observed_Values

array([[60, 97],
       [33, 54]], dtype=int64)

In [68]:
print(f"observed value(real value) \n {dataset_array}")

observed value(real value) 
 [[60 97]
 [33 54]]


In [65]:
import scipy.stats as stats

In [119]:
stats_test,p_value,dof,Expected_Values = stats.chi2_contingency(dataset_array)

In [73]:
stats_test

0.0

In [74]:
p

1.0

In [75]:
dof

1

In [99]:
Expected_Values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [80]:
no_of_rows=dataset_tabole.iloc[0:2,0]

In [85]:
len(no_of_rows)

2

In [78]:
dataset_tabole

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [82]:
no_of_columns = dataset_tabole.iloc[0,0:2]

In [84]:
len(no_of_columns)

2

In [88]:
dof = (len(no_of_rows)-1)*(len(no_of_columns)-1)

In [89]:
dof

1

In [90]:
from scipy.stats import chi2

In [102]:
for o,e in zip(observed_Values,Expected_Values):
    print(o,e)

[60 97] [59.84016393 97.15983607]
[33 54] [33.15983607 53.84016393]


In [104]:
chisquare_test = sum([(o-e)**2./e for o,e in zip(observed_Values,Expected_Values)])

In [105]:
chisquare_test

array([0.00119737, 0.00073745])

In [115]:
chi_square_statistics = chisquare_test[0]+chisquare_test[1]

In [116]:
chi_square_statistics

0.001934818536627623

In [108]:
alpha=0.05

In [112]:
critical_value = chi2.ppf(1-alpha,df=dof)

In [113]:
critical_value

3.841458820694124

In [117]:
if chi_square_statistics>=critical_value:
    print("Reject H0, There is a relationship between 2 categorical variables")
else:
    print("Retain H0, There is no relationship between 2 categorical variables")

Retain H0, There is no relationship between 2 categorical variables


In [122]:
#p-value
p_value = 1-chi2.cdf(x=chi_square_statistics,df=dof)

In [123]:
if p_value>=alpha:
    print("Reject H0, There is a relationship between 2 categorical variables")
else:
    print("Retain H0, There is no relationship between 2 categorical variables")

Reject H0, There is a relationship between 2 categorical variables
